language: java
jdk: openjdk8
before_install:
- chmod +x mvnw
notifications:
  slack:
    secure: mKSVyxv+iC+FkGCMT11xPAuJwHG3zkhP660+kUdOyzgAy2WGNAcpwaDH8y8S0Q4zlOdeAv5OzV3onxKUPAGXCtXskpuu7pWpiMzFZGcUvkLQEA+WUqxZcv+x/WLVcnNRMpOctpkpZnVykqULouq0g9uhiwin4OKqpjwpWeQKZ13kMYesepJGYZrYetE+snzJOgEmfmwBsZ2+XL6tE6cdflwLEB/rmwloRYy3YGLVgmWTWk6oaXRlEn85YAqPXakwl1UhVgivKuFmBxgRzopqK8LIChCa5KlgQghR/TYQeI4bXrklXiqNZQBw9zIBQH74mwUb6OiHPsz+pK+iQAyO+OAJl9e6ElII5p8HjkO/RSvWvtoUyjIgU/wcDfE4CUC/Vv0PwCw7BAMoEb6SkICddMHShkwJ+XqFk532Qz+RiDi3vTakbMHB5SY6PsQiLcp2yOQhGx2I8eQrpEa+U1zQVFmp/54TkD3OQ7ZQNojFOIapY4qfMTCZTx7tdJdjejcXc0q26kUaWQxNylJ1a2bkRcm01SvQdlC78vVtyZAQ1IN6THmymvmts4wXDyM02G5Q5jmKBD5gcoAE4a5uM34oSKfNPQW8ZbdSTXP9mc623pt9zVHEqPkn+IlNLAaPfVL2h59sbEs9ZrBtbgzCpBz/dbrhiDfzTrk5hcgHbF5Iymw=
