language: java
jdk: openjdk8
before_install:
- chmod +x mvnw
notifications:
  slack:
    secure: vGGYgHZ3gw+fgygyTstAgzVXx4LiN+hT1i+EeyVZQucwPcqLrDBz+esdyMVpiP+kM5m19qKqa/cRqpZ+5uXpti6+9/N5dANpPiBiP3eFo0eLjzR0KgXtU3/BbyX+SzpFisA121Qpx4xSuZDnk3SxOVOl70k81Yvity23BT7QFodva2TYeZItdufK3HaDmXmuVjNCPD71WrrOzbxHc1kVfszE8s2px753yTwNH0z0/QjNdNoG8nGAuzsrN2uC+nvqMi6uQ62Bpne+Q7ulDy71IlDk89Lqd1vvTzKnNCvVotuF6KrAJ1dzZJgn/o6C3VdaJw9MGsONpR9bi4R//dXwaew6liyzTRzEF5JXv/d1+f4jGx4QzYqRxJNj0jn0piCoHS/uh3tXsPO2Eyn7iZlZK7M21Y5Ig0Rtgl6vMii/CYN1akFatIonrEVknuh7nnt7d65x/6Js0pZTYYWca80NZuElE2VZqwTCyO7qdRmB1hZE6q2i2NFE4nfYlK0bXMn6QzFvh17GIDaBZD+TSk7t27KaEYnJoIRJYw57z+HOFn4hrDF1zgnO6CZVqPu9rO8W8NKCq7xBmWvXrqJFC7Sohcnsdo0QpGE2oL9+yPQjXzgtsIshRWEien0eDknhNdTjR+4A1V14omKtX2oPcDh6ScIyLp1QKk0unyFkKodm/aY=
